FROM alpine:3.7
RUN apk add --no-cache python3 py3-pip jq  && pip3 install --upgrade pip \
    && pip3 install awscli && rm -rf /var/cache/apk/*
COPY init.sh /init.sh
COPY scripts /scripts/
RUN chmod 755 /init.sh /scripts/ -R

ENTRYPOINT ["/init.sh"]
CMD ["help"]
